repos:
  # Python代码格式化
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=100]

  # 导入语句排序
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]

  # 代码质量检查
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=100, --extend-ignore=E203,W503]

  # 基础文件检查
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # 检查文件末尾是否有换行符
      - id: end-of-file-fixer
      # 去除行末空白字符
      - id: trailing-whitespace
      # 检查YAML文件格式
      - id: check-yaml
      # 检查JSON文件格式
      - id: check-json
      # 检查是否有巨大的文件被提交
      - id: check-added-large-files
        args: ['--maxkb=1000']
      # 检查合并冲突标记
      - id: check-merge-conflict
      # 修复Python编码声明
      - id: fix-encoding-pragma
        args: [--remove]
      # 检查Python语法
      - id: check-ast

  # 类型检查（可选，因为可能会很严格）
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.5.1
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-requests, types-Pillow]
  #       args: [--ignore-missing-imports, --no-strict-optional]

# 配置选项
default_stages: [commit]
fail_fast: false

# 排除的文件
exclude: |
  (?x)^(
      build/.*|
      dist/.*|
      \.eggs/.*|
      .*\.egg-info/.*|
      __pycache__/.*|
      \.pytest_cache/.*|
      \.mypy_cache/.*|
      logs/.*|
      release/.*
  )$ 